### ISSUE TITLE
Asset conversion error

### ISSUE THREAD

**Issue by copyrat90** [Meepster99/GBAStranger#2]
Asset conversion is broken for me, maybe it's due to the recent `UndertaleModCli` changes?

```
Attempting to execute '1...\GBAStranger\misc\Scripts\ExportAllSpritesWithPadding.csx'...
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: ...\GBAStranger\misc\Scripts\ExportAllSpritesWithPadding.csx(23,8): error CS1061: 'TextureWorker' does not contain a definition for 'Cleanup' and no accessible extension method 'Cleanup' accepting a first argument of type 'TextureWorker' could be found (are you missing a using directive or an assembly reference?)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at UndertaleModCli.Program.RunCSharpCode(String code, String scriptFile) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 743
Attempting to execute '1...\GBAStranger\misc\Scripts\ExportAllTexturesGrouped.csx'...
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: ...\GBAStranger\misc\Scripts\ExportAllTexturesGrouped.csx(38,8): error CS1061: 'TextureWorker' does not contain a definition for 'Cleanup' and no accessible extension method 'Cleanup' accepting a first argument of type 'TextureWorker' could be found (are you missing a using directive or an assembly reference?)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at UndertaleModCli.Program.RunCSharpCode(String code, String scriptFile) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 743
Attempting to execute '1...\GBAStranger\misc\Scripts\ExportFontData.csx'...
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: ...\GBAStranger\misc\Scripts\ExportFontData.csx(10,22): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at UndertaleModCli.Program.RunCSharpCode(String code, String scriptFile) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModCli\Program.cs:line 743
initial setup completed
running massFormatter
converting tiles
Traceback (most recent call last):
  File "...\GBAStranger\misc\convertAllAssets.py", line 186, in <module>
    massFormatter.massFormatter.main()
  File "...\GBAStranger\misc\massFormatter\massFormatter.py", line 1743, in main
    convertTiles("./formattedOutput/tiles/")
  File "...\GBAStranger\misc\massFormatter\massFormatter.py", line 364, in convertTiles
    contents = os.listdir(inputPath)
               ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] path not found: '../ExportData/Export_Textures/Backgrounds/.'
```

**Comment by Meepster99** [comment]
sorry for my delay
its same on my end. thanks for letting me know
ill get back to you once i hopefully have a solution

**Comment by Meepster99** [comment]
1e498f23b71bf78bb30e7cb6104777cbc5634199 fixes this, finally switched over to using a constant version of UMT
