### ISSUE TITLE
massFormatter no such file or directory error (windows)

### ISSUE THREAD

**Issue by mushcalli** [Meepster99/GBAStranger#3]
getting "FileNotFoundError: [Errno 2] No such file or directory: './formattedOutput/allSprites\\\\dw_[first sprite to generate].bmp'" from massFormatter when attempting to run convertAllAssets.py, unsure if it's a mismatched slash direction issue or an issue with the folder never being created but replacing all the forward slashes in path strings with escaped backslashes didn't fix the error

end part of the output log:
```
Finished executing 'C:\Users\XX\Downloads\GBAStranger\misc\Scripts\ExportFontData.csx'
initial setup completed
running massFormatter
generating include file
generating spr_soulglow_med
Traceback (most recent call last):
  File "C:\Users\XX\Downloads\GBAStranger\misc\convertAllAssets.py", line 195, in <module>
    massFormatter.massFormatter.main()
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 1702, in main
    generateAllIncludes()
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 1678, in generateAllIncludes
    generateIncludes(["./formattedOutput/tiles/", "./formattedOutput/fonts/", "./formattedOutput/customFloor/", "./formattedOutput/customEffects/", "./formattedOutput/allSprites/"])
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 1570, in generateIncludes
    genSprite(spriteName, False)
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 1160, in genSprite
    convertSprite(spriteName, paddedSpriteImages, paddedSpriteSize, isBackground, isNormalBackground)
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 1074, in convertSprite
    writeBitmap(tempImage, os.path.join(outputPath, spriteName.lower() + ".bmp"))
  File "C:\Users\XX\Downloads\GBAStranger\misc\massFormatter\massFormatter.py", line 305, in writeBitmap
    with open(newDest, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './formattedOutput/allSprites\\dw_spr_soulglow_med.bmp'
```

**Comment by mushcalli** [comment]
My bad, I was passing "-X utf8=1" into the script args instead of the python args, after fixing that it runs fine and the mismatched slash directions are a non-issue
